[package]
name = "protocol"
version.workspace = true
edition.workspace = true

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
rga = { path = '../rga' }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0"
tokio = "1.48.0"
uuid = "1.19.0"
