[package]
name = "protocol"
version.workspace = true
edition.workspace = true

[dependencies]
rga = { path = '../rga' }
serde = { version = "1.0.228", features = ["derive"] }
tokio = "1.48.0"
uuid = "1.19.0"
