name: Build & Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'crates/**'
      - 'docker/**'
      - 'frontend/**'
      - '.github/workflows/ci.build-deploy.yml'

jobs:
  build-and-deploy:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v3

      - name: Pre-Clean
        run: |
          docker image prune -af

      - name: Build
        run: |
          docker compose --parallel 3 -f docker/ci/docker-compose.yml build

      - name: Deploy
        run: |
          docker compose -f docker/ci/docker-compose.yml down
          docker compose --parallel 3 -f docker/ci/docker-compose.yml up -d --build

      - name: Post-Clean
        run: |
          docker image prune -af
          docker system prune -f
